- name: "Set repo-pass-cmd as '{{ default_pass_cmd }}', in '{{ default_pass_cmd_file_path }}'"
  ansible.builtin.template:
    dest: "{{ default_pass_cmd_file_path }}"
    src: "default_pass_cmd.j2"
    force: true
  become: true
  become_user: "{{ restic_user_name }}"
  when: default_pass_cmd is defined

