- name: "Set repo-pass-cmd as '{{ restic_default_pass_cmd }}', in '{{ restic_default_pass_cmd_path }}'"
  ansible.builtin.template:
    dest: "{{ restic_default_pass_cmd_path }}"
    src: "default_pass_cmd_sh.j2"
    mode: '755'
    force: true
  become: true
  become_user: "{{ restic_user_name }}"
  when: restic_default_pass_cmd is defined

