- name: "Install restic application"
  ansible.builtin.include_tasks: install_app/main.yml

- name: "Configure remote repo access"
  ansible.builtin.include_tasks: config_repo_access/main.yml

- name: "Create restic config dir"
  ansible.builtin.include_tasks: create_config_dir/main.yml

- name: "Create restic utility script"
  ansible.builtin.include_tasks: create_util_script/main.yml

# - name: "Create restic user guide"
#   ansible.builtin.include_tasks: create_user_guide/main.yml
#   when: (restic_user_guide_dir)

- name: "Configure automatic backups"
  ansible.builtin.include_tasks: config_auto_backups/main.yml

