- name: "Create .cache directory for user '{{ restic_user_name }}'"
  ansible.builtin.file:
    path: "{{ restic_user_toplevel_cache_dir }}"
    state: directory
    owner: "{{ restic_user_name }}"
    mode: '755'
  become: true
  become_user: root

- name: "Create restic cache dir as zfs dataset"
  ansible.builtin.include_tasks: dataset_cache_dir/main.yml
  when: use_zfs_dataset_for_restic_cache_dir

- name: "Create restic cache dir as normal filesystem directory"
  ansible.builtin.include_tasks: fs_cache_dir/main.yml
  when: not use_zfs_dataset_for_restic_cache_dir

