# main user dirs for config, cache
restic_user_config_dir: "/home/{{ restic_user_name }}/.config"
restic_user_cache_dir: "/home/{{ restic_user_name }}/.cache"

# dir that holds child config dirs
restic_config_dir: "{{ restic_user_config_dir }}/restic"

# dir that holds remote repo keys (_NOTE_: don't access directly - use script)
restic_keys_dir: "{{ restic_config_dir }}/keys"

# dir that holds encyrption sync info between local files and remote repo
restic_security_dir: "{{ restic_config_dir }}/security"

# dir for cache/sync info between local files and remote repo
restic_cache_dir: "{{ restic_user_cache_dir }}/restic"

# create and use zfs datasets for all restic config dirs
use_zfs_datasets_for_restic_configs_dirs: true

# if using zfs datasets for config dirs, use this zpool
restic_config_dir_zpool: 'zroot'

