- name: "Create restic config dir for user '{{ restic_user_name }}' at '{{ restic_config_dir }}'"
  ansible.builtin.file:
    path: "{{ restic_config_dir }}"
    state: directory
  vars:
    restic_config_dir: "{{ restic_default_passwd_keystr_file_path | dirname }}/restic"
  become: true
  become_user: "{{ restic_user_name }}"

